---
title: "TE Introducción"
description: |
  Presentación de la asignatura y logística <br/> Descripción del proyecto común <br/> Introducción a los patrones de diseño.
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Organización clase

-   [40 min] **Opening**: [Bienvenidos a la EI1039](index.html) (y EI1048), logística y presentación de la asignatura

-   [20 min] **Presentación:** Proyecto común de EI1039/EI1048, con hincapié en aspectos de la EI1039

    -   [Bootcamps o programas intensivos de formación IT](https://blog.talenthackers.net/mejores-bootcamps-y-programas-de-formacion-para-perfiles-it-en-espana#Los_mejores_bootcamps_o_programas_de_estudio_para_ingeniero_de_Software). Los campamentos de entrenamiento de codificación son programas intensivos e inmersivos que enseñan a las personas las habilidades que necesitan para convertirse en desarrolladores de software. Por lo general, duran unos meses y cubren lenguajes de programación, algoritmos y **principios de ingeniería de software**.

    -   [Bootcamps para ingeniero de Software: 4 Geeks Academy](https://4geeksacademy.co/es/course/ingenieria-de-software-programacion)

-   [25 min] **Presentación**: [Patrones de Diseño: Concepto, catálogo y principios](slides/TE1_intro_patrones.html)

    -   Definición de patrón de diseño

    -   Categorías de patrones: creacionales, estructurales, y de comportamiento

    -   Principios comunes a los patrones

-   [15 min] **Video**: [Patrones de diseño software: Repaso completo en 10 minutos (by Antonio Leiva)](https://www.youtube.com/watch?v=6BHOeDL8vls)

-   [10 min] **Closing**: Actividad 2.1
