---
title: "TE Fundamentos arquitectura"
description: |
  Fundamentos de arquitectura: conceptos, roles y compromisos <br/>
  Fundamentos de arquitectura: características <br/>
  Fundamentos de arquitectura: estilos
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Organización clase

-   [05 min] **Opening**

-   [10 min] **Revisión**: Actividad 2.1

-   [25 min] **Presentación**: [Fundamentos de arquitectura: conceptos y roles](slides/TE2_fundamentos_arquitectura.html)

    -   Definición de *arquitectura de software*

    -   Tareas de un arquitecto de software

    -   Arquitecto *vs* diseñador/desarrollador

-   [25 min] **Presentación**: [Fundamentos de arquitectura: características](slides/TE2_caracteristicas_arquitectura.html)

    -   Definición de características de arquitectura; dimensiones (operacionales, estructurales, horizontales)

    -   Identificación de las características relevantes para un sistema

    -   Todo en arquitectura de software tiene compromisos

-   [25 min] **Presentación**: [Fundamentos de arquitectura: Estilos de arquitectura](slides/TE2_estilos_arquitectura.html)

    -   Estilos monolíticos vs. distribuidos

-   [10 min] **Closing**: Actividad 3.1

## 
