---
title: "todo"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# ¿Por qué?

Siguiendo la línea del método investigacion-acción para la mejora docente contínua. Ver artiíulo [Investigación práctica en educación: investigación-acción](https://upcommons.upc.edu/handle/2099/12000).

# TE1

1 hora para introducir la asignatura + 1 hora sobre material sobre fundamentos de arquitectura. Se introduce arquitectura kata y se propone ejercicio en HW1

## Acciones de mejora

-   Replantear HW1? en base a la actividad POGIL de arquitectrua kata

# TE2

Dos actividades POGIL, una de iniciación a buenas practicas de equipos/roles y otra de arquitectura kata. No da tiempo a la presentación "estilos de arquitectura". PROBLEMA de tiempo!!

## POGIL - Buenas practicas

-   Cuesta formar equipos. Pero una vez configurados, las cosas parece que funcionan.
-   Los tiempos de ejecución reportadas por los equipos son razonables a los previstas.
-   Contextualizar mejor las preguntas, por ejemplo, relacionar con la informática y con equipos de desarrollo software, en vez de utilizar generalidades como "carrera profesional" etc.

## POGIL - Arquitectura kata

Creo que esta actividad es candidata a eliminar en próximas ediciones. Tal vez, replantear como HW1.

## Acciones de mejora

-   Que sepan que hay feedback. Necesitan resumenes frecuentas de las actividades POGIL desarrolladas hasta ahora.
-   Ajustar planificación: ¿Dos actividades POGIL en la misma sesión parece demasiado?
-   Actualziar tiempo estuimado POGIL kata: Modelo 1: 10 min, Modelo 2: 20 min

# TE3

Se plantean uan presentacion de introducción a los patrones + actividad POGIL para SIngleton + presentación de Factory Method (con preguntas a grupos). El HW asociado es una continuación de la presentacion de Factory Method.

Otra vez falta de tiempo. La segunda presentación sobre Factory Method fue demasiado rápida. No es posible realizar tres actividades en una misma sesión (2 presentaciones + 1 POGIL o 2 POGIL + 1 presentación). Solución es incluir una actividad de cada tipo en cada sesión. ¿En que orden? Me parece que mejor forma es primero presentacion, seguida de actividad POGIL

## POGIL - Singleton

Las preguntas son muy simples. pero el ejercicio de desarrollo hace que el timpo previsto se queda corto. Tal vez porque es la primera vez qeu paper rol de programador. Para la proxima edicion, la estructura de la sesion puede ser: presentación de Singleton + Factory methods, seguoid de actividad pogicl combinada para los dos patrones. Aun queda el problema de programar. Utilizar editor cloud? Para los scripts/clases de los actividades parece posible. De todoas forma, anticipar mecanismo para la programacion antes de la actividad, para que los estudiantes vengan preparados y no pierdan tiempo.

## HW3 - Factory Method

Errores comunes - diagrama UML no refleja las relaciones entre clases. Interfaz con todas sus implementaciones (implements) con flechas discontinuas y con la punta blanca sin relleno. Clase abstracta y sus implementaciones (extends) con flechas continuas con la punta blanca sin relleno. Composición con flecha discontinua con punta simple

# TE4

Se plantea como revisión + presentación contenido en la primera hora. Luego, actividad POGIL en la segunda hora. El ritmo de la clase ha ido mejor, aunque siempre acumulo retraso y siempre lo paga la actividad POGIL.

Facade puede esconder una Interface. Plantear como ejercicio que esconda varias interfaces? ¿Puedes combinar Singleton con Facade?

# TE5

Empezar los primeros 15 minutos con la terminación de la actividad POGIL de la TE4. Corregir en clase. Luego, presentacion de los patrones Composite + Decorator, seguida de una actividad POGIL sobre el composite y cmo HW, una actvidad sobre el Decorator a parti de la solucion del composite desarrollada en la actividad POGIL.

# TE6

La actividad POGIL funcioana bien! Solo tengo 4 grupos, y la interaccion dentro de cada grupo funciona Tal vez, la actividad parece lo suficiente interesante para que exista discussion entre los miembros. Voy a mostart la solución en la propia clase, a diferencia de actividades POGIL en sesiones anteriores. Feedback earlier!

# TE7

Tengo que encontrar un mecanismo para que el codigo qeu escriben los estydiantes en una actividad POGIL de progrmación lo pueden registrar y yo evaluarlo de alguna forma, para que ellos reciban feedback y que sepan que lo miro. [GitHub Codespace](shttps://code.visualstudio.com/docs/remote/codespaces), [vscode cloud](https://www.vscodecloud.com/), github gist for java?, etc.

HW5: Reformular el ejercicio para que las metricas sea un argumento a los clasificadores (joan/pardo); o como un metood setMetric() en al la interfac del Classifier (MA Prosper)?

# Acciones para proximas ediciones

-   Reestructurar la web como el curso de RRP. Añadir estilos como en <https://emitanaka.org/> y <https://jhelvy.github.io/distillery/showcase.html>. De este último website, me ha gustado el siguiente estilo <https://www.fizzics.ie/> para la web RRP. Para simplificar, utilizo un estilo muy simple para las asignturas de grado (EI1039) y master (Data Science), como este <https://cdu-data-science-team.github.io/team-blog/> o <https://sean.rbind.io/>, para cambiar únicamente el color de cabecera (y links, etc) en cada curso académico.

-   ¿Alguna forma de comunicar los patrones de diseño o su aplicación como una documento dinámico, al estilo de <https://distill.pub/2020/communicating-with-interactive-articles/>? ¿Podria ser un ejercicio a los alumnos?

-   Trasladar a la docencia los avances científicos más reciente en diseño de patrones. Eliminar algunas actividades POGIL (un par, por ejemplo) para utilizar sesiones magistrales de avances, novedades y tendencias más recientes. No es necesario que sean seguidadas. Pero esa presentacion de tendencias debe conectarse con el conocimiento previo anterior.

-   Modelo 5E (que sale en la presentacio decharlas.es de Hector Ruiz, <https://www.youtube.com/watch?v=KJ3xQZDNjK4&t=15s>) conecta bien con modelo POGIL)

-   Crear (entre el alumnado) fichas resumen de los patrones con una estructura común:

    -   Nombre

    -   Propósito

    -   Problema

    -   Estructura: solución conceptual vista como estructur de clase genérica

    -   Aplicabilidad: situaciones en las cuales el patrón tiene sentido,

    -   Ejemplos de código

    -   Relaciones con otros patrones

-   En HW posteriores, proponer la **autoevaluación** de la solución aportada con respecto a una solucion oficial, para explicar las diferencias entre la solución del alumno y la solución oficial. (ver [Presentación Merche](https://docs.google.com/presentation/d/e/2PACX-1vSuYiPuPinyEdonBrkUgJr8wPz4D_lZxYPvmnS3zPfhUYg5VvYxLF8sXbZL9IzUu0q0ADoPdIfSqhry/pub?slide=id.gee5a1a6ddf_0_4))

-   Para HW posteriores, proponer quizz o preguntas de reflexiones sobre las actividades POGIL desarrolladas en la sesión (forma de evaluar POGIL)

-   Plantear competencias basicas y avanzadas y erróres basicos/avanzados (ver [Presentacion Merche](https://docs.google.com/presentation/d/e/2PACX-1vSuYiPuPinyEdonBrkUgJr8wPz4D_lZxYPvmnS3zPfhUYg5VvYxLF8sXbZL9IzUu0q0ADoPdIfSqhry/pub?slide=id.gee5a1a6ddf_0_4))

-   Basado en las reflexiones personales de HW2, parece que el método POGIL es bien recibido por los estudiantes. Uff, menos mal!!

-   Plantear una sesion de seminario de "recent trends", al estido de lo que se comenta en este articulo <https://cacm.acm.org/magazines/2020/7/245690-your-wish-is-my-cmd/fulltext>, para la generacion de codigo automaticamente. ¿Como se relaciona con patrones? ¿y sobre la generacion de tests automaticos?

-   Primera parte de la primera sesion se debe reducir a 15 min. Estudiantes deben leer la guía docente extendida y syllabus antes de la primera sesion. Asi, arqhitecture software se reduce a una única sesión, y ganamos una sesión para introducer patrones de diseño y actividad pogil.

-   ¿Son las actividades POGIL necesarias en todas las clases?

-   Partir de los proyectos del curso 2021/22, para plantear ejercicios más realistas de patrones en POGIL HW.



-   Seminario conjunto de paradigmas/arquitecturas software. Plantear tipo debate entre dos equipos. Dado un caso de estudio concreto (aplicación bien conocida), plantear dos estilos arquitectónicos (A y B), para que cada equipo escoja una de ellos y defienda su postura, es decir, que el caso de estudio es mejor con la arquitectura A o es mejor con la B.

-   [5 Design Patterns every engineer should know](https://www.youtube.com/watch?v=FLmBqI3IKMA)

-   [UI-desing patterns](http://ui-patterns.com/patterns)

-   Añadir soporte blog para describir feedback, comentarios y demas sobre HW y actividades POGIL

-   Añadir contracto de aprendizaje para la primera sesion, con el fin de que los estundate se comprometan a realziar los HW

-   Encontrar modo de corregir y proporcionar feedback a los HW y actividades POGIL. Por ejemplo, los howeworks se pueden realizar todos en Github, con una estructura dada (ejemplo de repo mio), que combine ficheros readme y codigo. Los ficheros readme pueden incluir reflexiones tambien.

-   Nombrar (name) las slides clave de cada presentacion: inicio, estructura, participantes, etc, segun la organización para explicar un patron

-   Slides teoria: "solución" debe ser "participantes"; "estructura" debe ser "solución conceptual". Ver [Tackling Design Patterns](https://www.cs.up.ac.za/cs/lmarshall/TDP/TDP.html)

-   Seminario de presentacion publica <https://aenui.org/actas/pdf/JENUI_2019_019.pdf> <https://aenui.org/actas/pdf/JENUI_2013_002.pdf> <https://aenui.org/actas/pdf/JENUI_2011_025.pdf>

-   Articulos de investigación recientes sobre patrones y similares. Pueden ser parte del seminario de aspectos avanzados, o parte de un HW, o reflexión en grupo.

    -   [The state of research on software engineering competencies: A systematic mapping study](https://doi.org/10.1016/j.jss.2021.111183)

    -   [Research state of the art on GoF design patterns: A mapping study](https://doi.org/10.1016/j.jss.2013.03.063)

    -   [Designing and implementing an environment for software start-up education: Patterns and anti-patterns](https://doi.org/10.1016/j.jss.2018.08.060)

    -   [The state of the art on design patterns: A systematic mapping of the literature](https://doi.org/10.1016/j.jss.2016.11.030)

    -   [What can violations of good practices tell about the relationship between GoF patterns and run-time quality attributes?](https://doi.org/10.1016/j.infsof.2018.07.014)

    -   [Study of advanced separation of concerns approaches using the GoF design patterns: A quantitative and qualitative comparison](https://doi.org/10.1016/j.infsof.2014.04.015)

    -   [A study on correlations between architectural smells and design patterns](https://doi.org/10.1016/j.jss.2021.110984)

    -   [how Google practices software engineering](https://arxiv.org/ftp/arxiv/papers/1702/1702.01715.pdf)
