---
title: "HW5"
description: |
  Implementación patrón Strategy
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Objetivos de aprendizaje (contenido)

Después de completar esta actividad, los alumnos deberían poder:

-   Comprender la solución conceptual del patrón Strategy
-   Analizar la combinación de dos Strategies como solución conceptual
-   Implementar dos  Strategies en un caso particular

## Objetivos de proceso (soft skills)

Después de completar esta actividad, los alumnos deberían poder:

-   Evaluar e interpretar información para adoptarla a un contexto determinado (*Information processing*)
-   Transmitir información compresible a través de materiales escritos (*Written communication*).

## Entrega

-   Se entrega de forma individual en el Aula Virtual. Se deberá subir un documento en formato PDF. Puedes incluir un link en el propio documento al código creado si encuentra en un repositorio público.

-   Fecha límite: 3 nov, 23:59

## Actividades

La desarrolladora-jefe requiere de un nuevo simulador que facilite el testeo de una batería de clasificadores de Machine Learning: K-NN, K-means y Self-Organizing Map (SOM). Los tres clasificadores se basan en métricas de distancia para la predicción. Para mejorar la fiabilidad de las simulaciones, se decide utilizar dos métricas de distancia: Euclidean y Manhattan. Como resultado, el nuevo simulador admite hasta 6 combinaciones, ya que cada clasificador puede utilizar cualquiera de las 2 métricas para el cálculo de la distancia entre el nuevo dato y el conjunto de datos de entrenamiento. Vamos a realizar el simulador de forma progresiva. 


1. Considera inicialmente la batería de tres clasificadores. Dibuja el diagrama UML para aplicar el patrón `Strategy` al simulador que estamos implementando.

2. Implementa la interfaces y clases necesarias. La clase cliente (`DemoStrategySimple.java`) se incluye como ayuda, así como la salida por consola.

```{}
public class DemoStrategySimple {

    public static void main(String[] args) {
        System.out.println("--- KNN ---");
        ContextSimple context = new ContextSimple(new ClassifierKnn());
        context.run();

        System.out.println("--- K-means ---");
        context.setClassifierStrategy(new ClassifierKmeans());
        context.run();

        System.out.println("--- SOM ---");
        context.setClassifierStrategy(new ClassifierSOM());
        context.run();
    }
}

```

```console
--- KNN ---
ClassifierKnn executed
--- K-means ---       
ClassifierKmeans executed
--- SOM ---
ClassifierSOM executed
```


3. Extiende el simulador considerando ahora que las métricas de la distancia (Manhattan, Euclidea) se implementan también con el patron `Strategy`. Dibuja un diagrama UML ampliando el anterior (Actividad 1) con la composicion de dos estrategias. 


4. Implementa ahora la nueva interfaz y clases necesarias. Modifica, si fuera necesaria, alguna de las clases creadas en la Actividad 2. La implementación completa debe permitir que el simulador pueda combinar dos estrategias dinámicamente para ejecutar, por ejemplo, KNN con la distancia euclidea y luego ejecutar KNN con la distancia Manhattan. Se muestra la salida por consola de la ejecución de un programa cliente.


```console
--- KNN with Euclidean distance---
DistanceEuclidean computed
ClassifierKnn executed
--- KNN with Manhattan distance---
DistanceManhattan  computed
ClassifierKnn executed
--- K-means with Manhattan distance ---
DistanceManhattan  computed
ClassifierKmeans executed
--- SOM  with Euclidean distance ---
DistanceEuclidean computed
ClassifierSOM executed
```
