---
title: "HW6"
description: |
  Implementación patrón Command
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Objetivos de aprendizaje (contenido)

Después de completar esta actividad, los alumnos deberían poder:

-   Comprender la solución conceptual del patrón Command
-   Analizar otro tipo de usos o propósitos del patrón Command
-   Implementar propósitos variados del patrón Command en una misma solución

## Objetivos de proceso (soft skills)

Después de completar esta actividad, los alumnos deberían poder:

-   Evaluar e interpretar información para adoptarla a un contexto determinado (*Information processing*)
-   Transmitir información compresible a través de materiales escritos (*Written communication*).

## Entrega

-   Se entrega de forma individual en el Aula Virtual. Se deberá subir un documento en formato PDF. Puedes incluir un link en el propio documento al código creado si encuentra en un repositorio público.

-   Fecha límite: 10 nov, 23:59

## Actividades

Las actividades propuesta a continuación son una continuación de la actividad POGIL para el patrón Command realizada en la sesión TE8. Todos los miembros de cada equipo deberán tener el código desarrollado en esa actividad POGIL. A partir de ahora, las siguentes actividades se realizan individualmente.

El funcionamiento real del robot BeeBot no funciona de forma interactiva, es decir, los comandos asociados al presionar cada una de las teclas naranjas no se ejecutan inmediatamente (¡eso desesperaría al niño/a!), sino que se almacena la secuencia de comandos hasta que se presiona la tecla especial “GO” de color verde. Este es el objetivo principal de este HW. Lo implementaremos de forma progresiva.

1. Como primer paso, idea e implementa una forma de mantener la secuencia de comandos sin ejecutarlos inmediatamente. Deberás añadir una clase que soporte el histórico de comandos y modificar el código de algunas clases existente para que cada tecla presionada no conlleve la ejecución del comando asociado sino que lo almacena en una estructura de datos adecuada.


2. Ahora que tienes la secuencia de comandos (teclas presionadas) almacenada, idea e implementa una solución (comando) para recrear el otro botón especial de BeeBot que permite "borrar" la última (y solo la última) tecla naranja presionada. 


3. Ahora sí que está todo listo para que implementes el comportamiento real del botón especial verde “GO” del BeeBot (como un comando) que ejecuta la secuencia ordenada de teclas naranjas (comandos) almacenados. 

