---
title: "Syllabus"
description: |
  Esta programación temporal puede estar sujeta a cambios durante el curso.
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

::: {.l-page}
+--------+----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------+----------------------------------------------+--------------------------------------------------------------------+
| Semana | Fecha          | Pre (lecturas/videos)                                                                                                                                                                             | TE (viernes, 15:00-17:00)                                              | Post (homework)                              | LA/SE (viernes, 17:00-19:00)                                       |
+========+================+===================================================================================================================================================================================================+========================================================================+==============================================+====================================================================+
| 1      | 10-sep         | email                                                                                                                                                                                             | [TE1 Intro asignatura y arquitectura software](TE1.html)               | [Homework 1](HW1.html) (hasta 22-sep, 23:59) | NA                                                                 |
+--------+----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------+----------------------------------------------+--------------------------------------------------------------------+
| 2      | 17-sep         |                                                                                                                                                                                                   | NA                                                                     |                                              | NA                                                                 |
+--------+----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------+----------------------------------------------+--------------------------------------------------------------------+
| 3      | 24-sep         | Video: [What's is POGIL?](https://pogil.org/about-pogil/what-is-pogil) & web site [IntroCS-POGIL](http://introcspogil.org/)                                                                       | [TE2 Estilos architectura software](TE2.html)                          | [Homework 2](HW2.html) (hasta 29-sep, 23:59) | NA                                                                 |
|        |                |                                                                                                                                                                                                   |                                                                        |                                              |                                                                    |
|        |                | Blog: [Master Plan for becoming a Software Architect](https://azeynalli1990.medium.com/master-plan-for-becoming-a-software-architect-be7ba13f0999) (PDF en AV)                                    |                                                                        |                                              |                                                                    |
+--------+----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------+----------------------------------------------+--------------------------------------------------------------------+
| 4      | 01-oct         | Refresca los conceptos clave de Programación Orientada a Objetos.                                                                                                                                 | [TE3 Patrones creacionales: Singleton y Factory](TE3.html)             | [Homework 3](HW3.html) (hasta 6-oct, 23:59)  | **LA1**. Intro entrega \#1 proyecto                                |
|        |                |                                                                                                                                                                                                   |                                                                        |                                              |                                                                    |
|        |                | Video: [Singleton Pattern by Okhravi](https://www.youtube.com/watch?v=hUE_j6q0LTQ) (20min)                                                                                                        |                                                                        |                                              |                                                                    |
+--------+----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------+----------------------------------------------+--------------------------------------------------------------------+
| 5      | 08-oct         | "Sumérgete en los patrones de diseño". Ficha de [Adapter, Facade y Proxy](https://refactoring.guru/es/design-patterns/structural-patterns)                                                        | [TE4 Patrones estructurales: Adapter, Facade, y Proxy](TE4.html)       | No HW. En su lugar preparación SE1           | **LA2**                                                            |
|        |                |                                                                                                                                                                                                   |                                                                        |                                              |                                                                    |
|        |                | Video: [Adapter Pattern by Okhravi](https://www.youtube.com/watch?v=2PKQtcJjYvc) (26 min)                                                                                                         |                                                                        |                                              |                                                                    |
|        |                |                                                                                                                                                                                                   |                                                                        |                                              |                                                                    |
|        |                | Video: [Facade Pattern by Okhravi](https://www.youtube.com/watch?v=K4FkHVO5iac) (16 min)                                                                                                          |                                                                        |                                              |                                                                    |
|        |                |                                                                                                                                                                                                   |                                                                        |                                              |                                                                    |
|        |                | Video: [Proxy Pattern by Okharavi](https://www.youtube.com/watch?v=NwaabHqPHeM) (35 min)                                                                                                          |                                                                        |                                              |                                                                    |
+--------+----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------+----------------------------------------------+--------------------------------------------------------------------+
| 6      | 15-oct         | "Sumérgete en los patrones de diseño". Ficha de [Composite y Decorator](https://refactoring.guru/es/design-patterns/structural-patterns)                                                          | [TE5 Patrones estructurales. Composite y Decorator](TE5.html)          | [Homework 4](HW4.html) (hasta 20-oct, 23:59) | **LA3**. Intro entrega \#2 proyecto + **fecha límite entrega \#1** |
+--------+----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------+----------------------------------------------+--------------------------------------------------------------------+
| 7      | 22-oct         | "Sumérgete en los patrones de diseño". Ficha de [Observer](https://refactoring.guru/es/design-patterns/observer)                                                                                  | [TE6 Patrones de comportamiento: Observer](TE6.html)                   | No HW                                        | SE1 (con EI1048). Arquitectura Software                            |
|        |                |                                                                                                                                                                                                   |                                                                        |                                              |                                                                    |
|        |                | Video: [Observer pattern by Okhravi](https://www.youtube.com/watch?v=_BpmfnqjgzQ) (49 min)                                                                                                        |                                                                        |                                              |                                                                    |
+--------+----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------+----------------------------------------------+--------------------------------------------------------------------+
| 8      | 29-oct         | "Sumérgete en los patrones de diseño": Ficha de [Template Method](https://refactoring.guru/es/design-patterns/template-method) y [Strategy](https://refactoring.guru/es/design-patterns/strategy) | [TE7 Patrones de comportamiento: Template Method y Strategy](TE7.html) | [Homework 5](HW5.html) (hasta 3-nov, 23:59)  | **LA4**                                                            |
|        |                |                                                                                                                                                                                                   |                                                                        |                                              |                                                                    |
|        |                | Video: [5 Design Patterns Every Engineer Should Know](https://www.youtube.com/watch?v=FLmBqI3IKMA) (12 min)                                                                                       |                                                                        |                                              |                                                                    |
+--------+----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------+----------------------------------------------+--------------------------------------------------------------------+
| 9      | 05-nov         | "Sumérgete en los patrones de diseño": Ficha de [Command](https://refactoring.guru/es/design-patterns/command) y [Iterator](https://refactoring.guru/es/design-patterns/iterator)                 | [TE8 Patrones de comportamiento: Command y Iterator](TE8.html)         | Homework 6 (hasta 10-nov, 23:59)             | **LA5**                                                            |
+--------+----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------+----------------------------------------------+--------------------------------------------------------------------+
| 10     | 12-nov         |                                                                                                                                                                                                   | NA                                                                     |                                              | **LA6**. Intro entrega \#3 + **fecha límite entrega \#2**          |
+--------+----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------+----------------------------------------------+--------------------------------------------------------------------+
| 11     | 19-nov         |                                                                                                                                                                                                   | NA                                                                     |                                              | SE2 Patrón Model-View-Controller (MVC)                             |
+--------+----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------+----------------------------------------------+--------------------------------------------------------------------+
| 12     | 26-nov         |                                                                                                                                                                                                   | NA                                                                     |                                              | **LA7**                                                            |
+--------+----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------+----------------------------------------------+--------------------------------------------------------------------+
| 13     | 03-dic         |                                                                                                                                                                                                   | NA                                                                     |                                              | **LA8**                                                            |
+--------+----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------+----------------------------------------------+--------------------------------------------------------------------+
| 14     | 10-dic         |                                                                                                                                                                                                   | NA                                                                     |                                              | SE3 Interfaces Usuario                                             |
+--------+----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------+----------------------------------------------+--------------------------------------------------------------------+
| 15     | 17-dic         |                                                                                                                                                                                                   | NA                                                                     |                                              | SE4 Ensayo presentación proyecto                                   |
+--------+----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------+----------------------------------------------+--------------------------------------------------------------------+
|        | 23-dic , 23:39 |                                                                                                                                                                                                   |                                                                        |                                              | **Fecha límite entrega \#3**                                       |
+--------+----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------+----------------------------------------------+--------------------------------------------------------------------+
|        | ene 2022       |                                                                                                                                                                                                   |                                                                        |                                              | **Presentación proyecto**                                          |
+--------+----------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------+----------------------------------------------+--------------------------------------------------------------------+
:::
