---
title: "TE4 Patrones estructurales"
description: |
  Adapter, Facade y Proxy Patterns.
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Organización clase

-   [05 min] **Opening**

-   [25 min] **Revisión:** HW3

    > -   En general, implementación correcta.

    > -   [Diagrama UML](slides/images/students/HW3-UML.png) no siempre se corresponde con el código propuesto: relaciones interfaz-implementación (`implements`), relaciones clase abstracta-implementación (`extends`), relaciones entre clases (dependencia, asociación)
    > -  ¿Propósito [Factory Method](https://cgranell.github.io/ei1039/slides/TE3_2_factory.html#25)?  Una abstracción define un método de creación común, pero las subclases pueden modificar objetos creados. Método de creación unificada, pero objetos resultantes variados.

-   [30 min] **Presentación**: [Adapter pattern](slides/TE4_1_adapter.html), [Facade pattern](slides/TE4_2_facade.html) and [Proxy pattern](slides/TE4_3_proxy.html)

-   [50 min] **Actividad POGIL**: Adapter-Facade-Proxy patterns

    -   Grupos de 4-5 personas

    -   Asignación de roles, incluyendo **Programador**. Todos se bajan una copia de las *Role Cards* (AV)

    -   [Actividad POGIL (AV)](https://aulavirtual.uji.es/mod/resource/view.php?id=4604142)

-   [5 min] **Closing**

