---
title: "TE6 Patrones de comportamiento"
description: |
  Observer Pattern.
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Organización clase

-   [5 min] **Opening**

-   [10 min] **Revisión**: Entrega #1 proyecto común

-   [20 min] **Revisión**: [HW4](HW4.html)

    > -   Composite pattern: En la clase `Composite`, incluir [métodos](https://cgranell.github.io/ei1039/slides/TE5_1_composite.html#7) para gestionar el árbol.
    
    > -   Composite pattern: En el diagram UML propuesto, no olvidéis la relación de agregación porque permite la recursividad. 

    > -   Composite & Decorator pattern: [Diagrama UML de la solución](slides/images/students/HW4-UML.png): La clase asbtracta Decorator implementa la interfaz común, y permite crear `Concrete Decorators`. Por lo tanto, no implementar un único Decorador (Base y Concreto) porque rompemos el [principio de abierto/cerado](https://cgranell.github.io/ei1039/slides/TE3_1_patrones_diseno.html#33). Además, el poder del patrón Decorator está en la [pila de agregación](https://cgranell.github.io/ei1039/slides/TE5_2_decorator.html#7), para concatenar un numero variables de decoradores en tiempo de ejecución.

-   [30 min] **Presentación**: [Observer pattern](slides/TE6_1_observer.html)

-   [50 min] **Actividad POGIL**: Observer pattern

    -   Grupos de 4-5 personas

    -   Asignación de roles, incluyendo **Programador**. Todos se bajan una copia de las *Role Cards* (AV)

    -   Actividad POGIL (AV)

-   [5 min] **Closing** 

## 
